### ISSUE TITLE
Take over maintainership of Net::SAML2

### ISSUE THREAD

**Issue by alranel** [xmikew/perl-Net-SAML2#1]
Hello!

This looks like the most maintained fork of Net::SAML2 (thank you for working on this). It would be nice to get this code on CPAN.
It looks like the original maintainer of that module disappeared many years ago from the scene and is unresponsive. Did you try to contact modules@cpan.org to offer maintainership of the module? The procedure is documented here: http://www.cpan.org/misc/cpan-faq.html
I'm interested in helping.

**Comment by xmikew** [comment]
Hi,

There was a little buzz about JFEARN getting comaint that got started via this perl nntp thread:

https://www.nntp.perl.org/group/perl.modules/2017/02/msg97043.html

Neil Bowers got involved here:

https://www.nntp.perl.org/group/perl.modules/2017/03/msg97124.html

However, during an email thread hashing out the details JFEARN had to rescind his request for co-maint. chrisa is still around and was at the time attempting to get the code released open source from the employer he wrote the code for (who i think is now owned by oracle)

Anyhow, nobody has stepped up to request co-maint. I can hack it to get it to work for us at work but do not currently have the cycles to take over co-maint.

\- Mike

**Comment by waterkip** [comment]
Hi,

today I sent an email to CHRISA to apply for (co-)maintainership of the module. Maybe we can combine forces? 

Cheers,
Wesley

**Comment by jberger** [comment]
I'm also interested (and also emailed Chris before I saw this).

Meanwhile I'm also trying my hand at a totally independent implementation just in case. That said this would be much easier.

**Comment by xmikew** [comment]
There was a thread with Neil Bowers, Chrisa and a few others. I emailed them after Wesley's comment regarding the renewed interest in someone offering to take co-maint.

**Comment by xmikew** [comment]
Looks like neil bowers is stepping up to get comaint on this. Latest news.

**Comment by alranel** [comment]
FYI, in the mean time I had to work on a different implementation because of interoperability issues with our local context. In case anyone might be interested in looking at my code, which is a bit context-specific, here's it: https://github.com/italia/spid-perl

**Comment by timlegge** [comment]
For good or bad I was recently assigned the COMAINT role on Net::SAML2 and release a version 0.20 based on https://github.com/timlegge/perl-Net-SAML2 which was a fork of @alranel work which was a fork of @xmikew repo.

My fork has been tested against both a Microsoft and Google Identity provider.

If anyone is interested it is now on cpan as 0.20.  Thanks to everyone who contributed to making it work.

**Comment by xmikew** [comment]
Awesome! Thanks @timlegge for spending the time to get this all merged tested and on cpan.  I still use this fork in production and will be happy to get on the official repo! It’s been a long time coming. Thanks again!
