### ISSUE TITLE
Assertion not properly populating attribute values

### ISSUE THREAD

**Issue by timlegge** [xmikew/perl-Net-SAML2#2]
https://github.com/xmikew/perl-Net-SAML2/blob/710d85dd046c81fa284f78a2bb81bc41c7c6d20c/lib/Net/SAML2/Protocol/Assertion.pm#L63

Should be:
 my @values = ($node->findnodes('saml:AttributeValue'), $node);

according to https://rt.cpan.org/Public/Bug/Display.html?id=110896

**Comment by timlegge** [comment]
That seems to fix my issue with empty attributes

**Comment by xmikew** [comment]
Great thanks! I think there is a soon to be new maintainer of the official repo which will hopefully pull that bugfix in

**Comment by timlegge** [comment]
Any idea which of the various repos might be the most likely to be used as the base?  I am working on adding SAML support to a web app and I would like to start with a suportable version (and one that I could easily get back to the upstream with...

**Comment by xmikew** [comment]
Hi! Sorry missed your question and glad you got it sorted out.
